pipeline {

agent any

stages {

stage('Maven Compile'){

steps{

echo 'Project compile stage'

bat label: 'Compilation running', script: '''mvn -f 2assessment/pom.xml compile'''

}

}



stage('Unit Test') {

steps {

echo 'Project Testing stage'

bat label: 'Test running', script: '''mvn -f 2assessment/pom.xml test'''



}

}



stage('Jacoco Coverage Report') {

steps{

jacoco()

}

}



stage('SonarQube'){

steps{

bat label: '', script: '''mvn -f 2assessment/pom.xml sonar:sonar \

-Dsonar.host.url=http://localhost:9000 \

-Dsonar.login=d3f34b5cb51cb6ab4e94a5e6cc2f8840d7e867be'''

}

}



stage('Maven Package'){

steps{

echo 'Project packaging stage'

bat label: 'Project packaging', script: '''mvn -f 2assessment/pom.xml package'''

}

}



}

}
